apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default
spec:
  certificates:
    - secretName: mickelonius-tls
  defaultCertificate:
    secretName: mickelonius-tls
